jobs:
  - build-test-3_6:
      context: opensource
      filters:
        branches:
          ignore:
            - main
  - build-test-3_9:
      context: opensource
      filters:
        branches:
          ignore:
            - main
