description: Restores the build-test cache for pyenv, poetry, and pre-commit
steps:
  - restore_cache:
      keys:
        - v1-pyenv-{{ arch }}--{{ checksum "poetry.lock" }}
  - restore_cache:
      keys:
        - v1-poetry-{{ arch }}--{{ checksum "poetry.lock" }}
  - restore_cache:
      keys:
        - v1-precommit-{{ arch }}--{{ checksum ".pre-commit-config.yaml" }}
