description: Test building with Poetry, Cruft, pre-commit, and run unit tests with pytest.
parameters:
  python_version:
    description: Python version to use as the executor
    default: "3_9"
    type: enum
    enum: ["3_6", "3_7", "3_8", "3_9"]
executor: python-<< parameters.python_version >>-medium
steps:
  - add_ssh_keys:
      fingerprints:
        - "cb:4c:e2:f4:c2:be:b7:c0:1a:02:1b:13:15:e0:a4:1b"
  - ghpr/build-prospective-branch
  - aws-cli/install
  - circleci-cli/install
  - restore-test-cache
  - poetry-configure
  - bump-branch-version
  - run:
      name: Install dependencies
      command: poetry install
  - run:
      name: Build artifact with Poetry
      command: poetry build
  - run:
      name: Cruft check
      command: poetry run cruft check
  - run:
      name: Run commit hooks
      command: |
        poetry run pre-commit install
        poetry run pre-commit run \
          --source "origin/${GITHUB_PR_BASE_BRANCH}" \
          --origin "origin/${CIRCLE_BRANCH}" \
          --show-diff-on-failure
  - run:
      name: Run tests
      command: |
        mkdir -p test-results/unit
        poetry run pytest --junit-xml test-results/unit/results.xml
  - store-test-artifacts:
      artifacts_path: test-results
      export_test_results: true
  - save-test-cache
  - ghpr/slack-pr-author:
      when: on_fail
      message: ':ci-fail: Tests failed'
      get_slack_user_by: meseeks
      color: "#fcaaa3"
