description: Test building with Poetry, Cruft, pre-commit, and run unit tests with pytest.
executor: python-3_6-medium
steps:
  - add_ssh_keys:
      fingerprints:
        - "cb:4c:e2:f4:c2:be:b7:c0:1a:02:1b:13:15:e0:a4:1b"
  - ghpr/build-prospective-branch
  - aws-cli/install
  - circleci-cli/install
  - poetry-configure
  - bump-branch-version
  - run:
      name: Install dependencies
      command: poetry install
  - run:
      name: Build artifact with Poetry
      command: poetry build
  - run:
      name: Cruft check
      command: poetry run cruft check
  - run:
      name: Run commit hooks
      command: |
        poetry run pre-commit install
        poetry run pre-commit run \
          --source "origin/${GITHUB_PR_BASE_BRANCH}" \
          --origin "origin/${CIRCLE_BRANCH}" \
          --show-diff-on-failure
  - run: poetry run pytest --junit-xml .junit/unit/results.xml
  - store_test_results:
      path: .junit
  - ghpr/post-pr-comment:
      comment: Tests failed!
      when: on_fail
